### ISSUE TITLE
New API for installing ExtensionBundles

### ISSUE THREAD

**Issue by jenshalm** [planet42/Laika#56]
Bundles can define any of the available customizations:

* Directives
* Block Parsers
* Inline Parsers
* Rewrite Rules
* Custom Renderers

Potentially also support the more low-level features:

* DocType Matcher
* Template Engine

Parsers can define their own bundles, if they require custom rewrite rules or renderers.

The new API allows to install multiple extension with one API call. This new hook should be used by the new support for GitHub Flavored Markdown

**Task List**:

- [x] Define new API for ExtensionBundles
- [x] Use the new API with Laika's Parse, Render and Transform APIs
- [x] Process base config through ExtensionBundle
- [x] Process docTypeMatcher through ExtensionBundle
- [x] Process stylesheet parser through ExtensionBundle
- [x] Process rewrite rules through ExtensionBundle
- [x] Process default template and styles rules through ExtensionBundle
- [x] Process custom renderers through ExtensionBundle
- [x] Add Builder API for creating parser definitions
- [x] Implement Markdown's VerbatimHTML as an extension
- [x] Implement reStructuredText's ExtendedHTML as an extension
- [x] Implement Laika's Directives as an extension
- [x] Remove some of the old extension hooks, e.g. for TemplateParser, StylesheetParser
- [x] Allow to merge static files from a theme to the output tree
- [x] Centralize management of parsers for configuration headers
- [x] Refactor Markdown's core parsers to use the new Builder API
- [x] Refactor reStructuredText's core parsers to use the new Builder API
- [x] Implement reStructuredText's Directives as an extension
- [x] Simplify or remove old RootParsers
- [ ] Add documentation for creating ExtensionBundles to the manual
