### ISSUE TITLE
Update for sbt 1.0.x

### ISSUE THREAD

**Issue by larsrh** [planet42/Laika#57]
As far as I can tell, this entails the following steps:

* [x] bump plugin versions (all required plugins have 1.0.x support) (#58)
* [x] migrate from the legacy `Build` trait to `build.sbt` (#58)
* [x] (optional) enable Travis testing (#58)
* [x] migrate from legacy `Plugin` to `AutoPlugin`
* [x] build for sbt 1.0

I'm happy to volunteer for this. I have a patch ready for the first one, but I'm a little reluctant to submit without CI enabled.

**Comment by jenshalm** [comment]
Hi Lars, I am happy to accept PRs for any of the above.

* Regarding 1): do you mean to support cross-publishing to 0.13 and 1.0 or do you suggest to abandon 0.13 right away? I assume it is the former as 1.0 is not final yet.

* Regarding 2): there is already issue #53, you could commit against that ticket, I already had it on my list for 0.8, but I need to first finish the extensive performance improvements, before I look into the smaller things.

* Regarding 3): yes, that would be neat. Also on my todo-list for quite some time. Happy for you to work on that, otherwise I'd do it sometime later this year.

Regarding submitting without CI, it's fine if the tests run for you locally against all Scala and sbt versions, I'll rerun them locally before merging.

**Comment by larsrh** [comment]
1. Upgrading the plugin dependencies doesn't change anything for now. The next step after that would be to decide whether to cross-build or abandon 0.13. (As a side note: I'd argue for keeping 0.13 compatibility in a branch, and go 1.0 only in master. This is what many plugins have been doing. Others are cross-building, but that means additional overhead.)
2. Great, will do.
3. I'll also send a patch for this. You can just enable Travis and enjoy the benefits :smile:

**Comment by larsrh** [comment]
> I assume it is the former as 1.0 is not final yet.

Forgot to mention: While 1.0.0 final isn't out yet, 1.0.0-RC3 is binary compatible to 1.0.0 when it's going to be out. So targeting 1.0.x is not a problem.

**Comment by pcmehlitz** [comment]
any update on a plugin for SBT 1.0.x  ?
Thx

**Comment by jenshalm** [comment]
None unfortunately. There is a corresponding PR contribution, but that is incomplete, so could not just be merged and released and I did not find the time to finish it myself yet. The upcoming Christmas break might be an opportunity to complete this work, but as always, no guarantee.

**Comment by larsrh** [comment]
That PR is #59 (partially) and unfortunately I also didn't have time to follow through with this yet.

**Comment by jenshalm** [comment]
Changes for sbt 1.0 now available on the 0.7.5 branch. Actual release still pending, but will hopefully happen in the coming days. Will merge to master after the release.

**Comment by jenshalm** [comment]
Laika 0.7.5 with support for sbt 1.0 has been released today.
